Fix

diff --git a/.github/workflows/Feeds.yaml b/.github/workflows/Feeds.yaml
--- a/.github/workflows/Feeds.yaml
+++ b/.github/workflows/Feeds.yaml
@@ -35,7 +35,7 @@ jobs:
         run: pipenv run python rss.py dmzj && cat dist/dmzj.xml > /dev/null || echo "::set-output name=status::failed"
       - name: Generate ACG178
         id: acg178
-        run: pipenv run python rss.py acg178 && dist/acg178.xml > /dev/null || echo "::set-output name=status::failed"
+        run: pipenv run python rss.py acg178 && cat dist/acg178.xml > /dev/null || echo "::set-output name=status::failed"
       - name: Push RSS
         if: steps.dmzj.outputs.status != 'failed' || steps.acg178.outputs.status != 'failed'
         env:
