Update

diff --git a/.github/workflows/Feeds.yaml b/.github/workflows/Feeds.yaml
--- a/.github/workflows/Feeds.yaml
+++ b/.github/workflows/Feeds.yaml
@@ -10,7 +10,7 @@ on:
       - '.github/workflows/Feeds.yaml'
 
   schedule:
-    - cron: 0 4 * * *
+    - cron: 0 2 * * *
 
 jobs:
   feeds:
@@ -32,10 +32,10 @@ jobs:
           pipenv install
       - name: Generate DMZJ
         id: dmzj
-        run: pipenv run python rss.py dmzj || echo "::set-output name=status::failed"
+        run: pipenv run python rss.py dmzj && cat dist/dmzj.xml > /dev/null || echo "::set-output name=status::failed"
       - name: Generate ACG178
         id: acg178
-        run: pipenv run python rss.py acg178 || echo "::set-output name=status::failed"
+        run: pipenv run python rss.py acg178 && dist/acg178.xml > /dev/null || echo "::set-output name=status::failed"
       - name: Push RSS
         if: steps.dmzj.outputs.status != 'failed' || steps.acg178.outputs.status != 'failed'
         env:
